services:
  app:
    build: .
    container_name: "meteo"
    environment:
      SERVER_PORT: 3000 # Listen port
      METEO_CACHE_TTL: 4 # Cache time-to-live in hours
      METEO_TOKEN: "" # OpenWeatherMap API key
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3000:3000"