name: meteo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          apt -y update && apt -y install docker.io docker-compose
          ln -s compose.yml docker-compose.yml && docker-compose build
